language: php

php:
  - 5.4
  - 5.5

env:
  - ENV='travis'

services:
  - redis-server
  - memcached

before_install:
 - sudo apt-get install libevent-dev -qq
 - pear upgrade pear
 - pear channel-discover pear.phpunit.de
 - pear channel-discover components.ez.no
 - pear channel-discover pear.symfony.com
 - pear install --alldeps phpunit/PHPUnit
 - pecl install event eio
 - pecl install channel://pecl.php.net/proctitle-0.1.2
 - echo "extension=proctitle.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - echo "extension=event.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
 - echo "extension=eio.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
# - sudo apt-get update -y && sudo apt-get upgrade -y
  - composer self-update && composer --version && composer install
  - mysql -e 'CREATE DATABASE blog3;';
#  - tests/unit/data/travis/memcache-setup.sh
  - npm install -g bower
  - cd frontend/web && bower install && cd ../../
  - cd frontend/servers && npm install && cd ../../
  - php init travis

script:
  - phpunit --verbose
  - phpunit --coverage-clover frontend/tests/unit/runtime/coveralls/clover.xml --verbose

after_script:
  - php vendor/satooshi/php-coveralls/composer/bin/coveralls -v

notifications:
  email:
    recipients:
      - www.pismeco@gmail.com
    on_success: change # default: change
    on_failure: change # default: always