language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - CUBRID_VERSION=9.1.0

services:
  - redis-server
  - memcached

before_script:
  - composer self-update && composer --version && composer install
  - mysql -e 'CREATE DATABASE blog3;';
#  - tests/unit/data/travis/memcache-setup.sh
  - gem install bower
  - cd frontend/web && bower install && cd ../../
  - cd frontend/servers && npm install && cd ../../

script:
  - phpunit --coverage-clover tests/unit/runtime/coveralls/clover.xml --verbose --exclude-group mssql,oci,wincache,xcache,zenddata

after_script:
  - php vendor/bin/coveralls