language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - ENV='travis'

services:
  - redis-server
  - memcached

before_script:
  - composer self-update && composer --version && composer install
  - mysql -e 'CREATE DATABASE blog3;';
#  - tests/unit/data/travis/memcache-setup.sh
  - npm install -g bower
  - cd frontend/web && bower install && cd ../../
  - cd frontend/servers && npm install && cd ../../

script:
  - phpunit --coverage-clover frontend/tests/unit/runtime/coveralls/clover.xml --verbose

after_script:
  - php vendor/satooshi/php-coveralls/composer/bin/coveralls -v
