language: php

php:
  - 5.4
  - 5.5

env:
  - ENV='travis'

services:
  - redis-server
  - memcached

before_install:
 - sudo apt-get install libevent-dev -qq
 - pear upgrade pear
 - pear channel-discover pear.phpunit.de
 - pear channel-discover components.ez.no
 - pear channel-discover pear.symfony.com
 - printf "\n" | pecl install event eio
 - printf "\n" | pecl install channel://pecl.php.net/proctitle-0.1.2
 - composer self-update && composer --version && composer install

install:
  - mysql -e 'CREATE DATABASE blog3;';
  - npm install bower express socket.io jayson karma grunt-cli less phantomejs -g
  - cd frontend/web/js && npm install && cd ../../
  - cd frontend/web/js && bower install && cd ../../
  -  phantomjs --webdriver=4444

before_script:
# - sudo apt-get update -y && sudo apt-get upgrade -y
#  - tests/unit/data/travis/memcache-setup.sh
  - php init travis

script:
  - php vendor/codeception/codeception/codecept run acceptance

after_script:
  - php vendor/satooshi/php-coveralls/composer/bin/coveralls -v

notifications:
  email:
    recipients:
      - www.pismeco@gmail.com
    on_success: change # default: change
    on_failure: change # default: always